### ISSUE TITLE
feat: add temporary support for Rocky Linux 9

### ISSUE THREAD

**Issue by tcooper** [rocky-linux/createhdds#7]
## Description

See issue #6 in this repository for more information on supporting multiple releases of Rocky Linux in createhdds.

For now we need a workaround that will allow building HDDs for Rocky Linux 9 to support all tests in openQA.

## Expectation

`createhdds.py` builds virt-install images for Rocky Linux 9.

**Comment by lumarel** [comment]
We fixed that now!
